[package]
name = "git-anywhere-opendal"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
futures = { version = "=0.3.31", default-features = false, features = ["async-await", "std"] }
js-sys = "=0.3.104"
opendal = { version = "=0.58.1", default-features = false, features = ["services-opfs"] }
wasm-bindgen = "=0.2.127"
wasm-bindgen-futures = "=0.4.77"
web-sys = "=0.3.104"

[patch.crates-io]
opendal-service-opfs = { path = "vendor/opendal-service-opfs" }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = "symbols"
